### ISSUE TITLE
Persian Hershey Font

### ISSUE THREAD

**Issue by mkeyno** [tomw2/hersheyfontstuff#1]
hi , sorry to open ticket for my question , do you know instruction or software to convert specific fonts (Persian ) to Hershey fonts?

**Comment by tomw2** [comment]
I know of nothing that will do that.  However, when I searched, I found this:
https://www.evilmadscientist.com/2011/hershey-text-an-inkscape-extension-for-engraving-fonts/

it might help.  The specialized fonts we did for meteorological symbols were done manually.

 Good luck.
